# Generated by Django 3.1.2 on 2020-11-20 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('edition', models.CharField(max_length=50)),
                ('author', models.CharField(max_length=100)),
                ('location', models.CharField(choices=[('Dublin 1', 'Dublin 1'), ('Dublin 2', 'Dublin 2'), ('Dublin 3', 'Dublin 3'), ('Dublin 4', 'Dublin 4'), ('Dublin 5', 'Dublin 5'), ('Dublin 6', 'Dublin 6'), ('Dublin 7', 'Dublin 7'), ('Dublin 8', 'Dublin 8'), ('Dublin 9', 'Dublin 9'), ('Dublin 10', 'Dublin 10'), ('Dublin 11', 'Dublin 11'), ('Dublin 12', 'Dublin 12'), ('Dublin 13', 'Dublin 13'), ('Dublin 14', 'Dublin 14'), ('Dublin 15', 'Dublin 15'), ('Dublin 16', 'Dublin 16'), ('Dublin 17', 'Dublin 17'), ('Dublin 18', 'Dublin 18'), ('Dublin 19', 'Dublin 19'), ('Dublin 20', 'Dublin 20'), ('Dublin 21', 'Dublin 21'), ('Dublin 22', 'Dublin 22'), ('Dublin 23', 'Dublin 23'), ('Dublin 24', 'Dublin 24')], max_length=30)),
                ('genre', models.CharField(max_length=100)),
                ('year', models.IntegerField(max_length=10)),
                ('image', models.CharField(default='https://images.pexels.com/photos/4199098/pexels-photo-4199098.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940', max_length=300)),
            ],
        ),
    ]
