# Generated by Django 3.1.3 on 2020-11-29 14:46

from django.db import migrations
from django.contrib.postgres.operations import UnaccentExtension

class Migration(migrations.Migration):

    dependencies = [
        ('books', '0011_auto_20201122_1724'),
    ]

    operations = [
        UnaccentExtension()
    ]
