# Generated by Django 3.1.2 on 2020-12-13 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0012_auto_20201129_1446'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='contact',
            field=models.CharField(default=10, max_length=100),
            preserve_default=False,
        ),
    ]
