# Generated by Django 3.1.4 on 2020-12-13 20:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='date',
            field=models.CharField(default=datetime.datetime(2020, 12, 13, 20, 31, 32, 884549), max_length=100),
        ),
    ]
